export const TriviaActionConsts = {
  GET_TRIVIA_QUESTIONS_FETCHING: "GET_TRIVIA_QUESTIONS_FETCHING",
  GET_TRIVIA_QUESTIONS_SUCCESS: "GET_TRIVIA_QUESTIONS_SUCCESS",
  GET_TRIVIA_QUESTIONS_FAILURE: "GET_TRIVIA_QUESTIONS_FAILURE",
  TRIVIA_QUESTIONS_RESET: "TRIVIA_QUESTIONS_RESET",
};
